### ISSUE TITLE
No Twitter post preview

### ISSUE THREAD

**Issue by qbait** [Amitbhave/flutter-simple-url-preview#23]
Currently the package is not previewing Twitter posts correctly.

E.g. https://twitter.com/peterschiff/status/1504082706598146058?s=21
won't show correctly post preview

<img width="531" alt="Screenshot 2022-03-18 at 12 48 35" src="https://user-images.githubusercontent.com/2264901/158998067-27029275-1c17-49b4-b5af-65954d532dd7.png">

**Comment by Amitbhave** [comment]
Hi @qbait , unfortunately I found following issue with showing twitter's opengraph parameters:
https://stackoverflow.com/questions/62526483/twitter-website-doesnt-have-open-graph-tags
