### ISSUE TITLE
Make Container padding configurable

### ISSUE THREAD

**Issue by paurakhsharma** [Amitbhave/flutter-simple-url-preview#3]
Currently, the Container has a hard-coded padding of `const EdgeInsets.all(10),` 
But I need to display the list of URL previews, so I get unnecessary gap between the list elements.

It would be great if the padding was configurable

**Comment by Amitbhave** [comment]
Thanks for raising issue!
Padding has been made configurable now. Use version 1.0.0
Example: 
`previewContainerPadding: EdgeInsets.all(10),
`

**Comment by paurakhsharma** [comment]
Thank you so much for the prompt fix 😁
