### ISSUE TITLE
Make onTap configurable

### ISSUE THREAD

**Issue by paurakhsharma** [Amitbhave/flutter-simple-url-preview#4]
Currently, the Link Preview Container opens the URL in the browser when tapped.

But it would be great if we could pass our own custom `onTap` method

**Comment by Amitbhave** [comment]
onTap is also made configurable now as part of release 1.0.0.
By default it will open URL in default browser, but you can pass your own onTap callback as well.
`onTap: () => print('Hello Flutter URL Preview'),`

**Comment by paurakhsharma** [comment]
Thank you so much for the prompt fix 😁
